services:
  # Monolito (Backend FastAPI + Frontend React Unificado)
  - type: web
    name: citas-medicas-app
    env: docker
    region: ohio
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false 
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60