from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
import os
from app.database import engine, Base

from app.routers import auth, medicos, citas

# Opcional: Crear tablas si no existen (en Supabase ya están, pero es seguro llamarlo de todos modos, ignora si ya existen)
# Base.metadata.create_all(bind=engine)

app = FastAPI(title="Citas Médicas API", version="1.0.0")

# CORS Configuration for Next.js Frontend
origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://citas-medicas-app.onrender.com",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(medicos.router)
app.include_router(citas.router)

@app.get("/api")
def read_root():
    return {"message": "API de Citas Médicas corriendo correctamente. Visita /docs para la documentación."}

# Mount static files folder
STATIC_DIR = os.path.join(os.path.dirname(__file__), "..", "static")

if os.path.exists(STATIC_DIR):
    app.mount("/_next", StaticFiles(directory=os.path.join(STATIC_DIR, "_next")), name="next")
    
    # Static files normally generated by Next.js
    for static_folder in ["assets", "images", "fonts"]:
        folder_path = os.path.join(STATIC_DIR, static_folder)
        if os.path.exists(folder_path):
            app.mount(f"/{static_folder}", StaticFiles(directory=folder_path), name=static_folder)

    # Catch-all route to serve the React app
    @app.get("/{full_path:path}")
    async def serve_frontend(request: Request, full_path: str):
        # Prevent API routes from falling here
        if full_path.startswith("api/") or full_path.startswith("auth/") or full_path.startswith("medicos/") or full_path.startswith("citas/") or full_path.startswith("especialidades/"):
            return FileResponse(os.path.join(STATIC_DIR, "index.html")) # Or let the router handle it
            
        file_path = os.path.join(STATIC_DIR, full_path)
        if os.path.isfile(file_path):
            return FileResponse(file_path)
            
        # If the file does not have an extension, try appending .html since next export drops extension
        html_path = f"{file_path}.html"
        if os.path.isfile(html_path):
             return FileResponse(html_path)

        # Fallback to index.html for SPA routing
        return FileResponse(os.path.join(STATIC_DIR, "index.html"))
